learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
""" define learning_los's urlpatterns """

from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
	# 主页
	path('', views.index, name='index'),
	path('topics/', views.topics, name='topics'),
	path('topic/<int:topic_id>', views.entries, name='topic'),
	path('new_topic/', views.new_topic, name='new_topic'),
	path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
	path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
	path('delete_topic/<int:topic_id>', views.delete_topic, name='delete_topic'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
	# 包含默认的身份认证URL
	path('', include('django.contrib.auth.urls')),
	# 注册页面
	path('register/', views.register, name='register')
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
	topic_name = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		return self.topic_name

class Entry(models.Model):
	topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
	content = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural="entries"

	def __str__(self):
		if len(self.content) > 50:
			return f"{self.content[:50]}..."
		return self.content

users/models.py
from django.db import models

# Create your models here.

learning_logs/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic,Entry
from .form import TopicForm,EntryForm
# Create your views here.
def index(request):
	""" 学习笔记的主页 """
	return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
	""" 获取所有Topic页面 """
	topics = Topic.objects.filter(owner=request.user).order_by('date_added')
	context = {'topics':topics}
	return render(request, 'learning_logs/topics.html', context)

@login_required
def entries(request, topic_id):
	""" 获取指定Topic的所有条目 """
	topic = Topic.objects.get(id=topic_id)
	if request.user != topic.owner:
		raise Http404
	entries = topic.entry_set.order_by('date_added')
	context = {"topic":topic, "entries":entries}
	return render(request, 'learning_logs/entry.html', context)

@login_required
def new_topic(request):
	""" 用于创建新Topic """
	if request.method != 'POST':
		form = TopicForm()
	else:
		form = TopicForm(data=request.POST)
		if form.is_valid:
			new_topic = form.save(commit=False)
			new_topic.owner = request.user
			new_topic.save()
			return redirect('learning_logs:topics')
	context = {'form':form}
	return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
	topic = Topic.objects.get(id=topic_id)
	if request.method != 'POST':
		form = EntryForm()
	else:
		form = EntryForm(data=request.POST)
		if form.is_valid:
			new_entry = form.save(commit=False)
			new_entry.topic = topic
			new_entry.save()
			return redirect('learning_logs:topic',topic_id=topic_id)
	context = {'form':form, 'topic':topic}
	return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
	entry = Entry.objects.get(id=entry_id)
	topic = entry.topic
	if topic.owner != request.user:
		raise Http404
	if request.method != 'POST':
		form = EntryForm(instance=entry)
	else:
		form = EntryForm(instance=entry, data=request.POST)
		if form.is_valid:
			form.save()
			return redirect('learning_logs:topic', topic_id=topic.id)
	context = {'form':form,'entry':entry, 'topic':topic}
	return render(request, 'learning_logs/edit_entry.html', context)

@login_required
def delete_topic(request, topic_id):
	topic = Topic.objects.get(id=topic_id)
	if topic.owner != request.user:
		raise Http404
	topic.delete()
	return redirect('learning_logs:topics')

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def register(request):
	""" 注册新用户 """
	if request.method != 'POST':
		# 显示空的注册表单
		form = UserCreationForm()
	else:
		# 处理填写好的表单
		form = UserCreationForm(data=request.POST)
		if form.is_valid:
			new_user = form.save()
			# 让用户自动登录，重定向到主页
			login(request, new_user)
			return redirect('learning_logs:index')
	context = {"form":form}
	return render(request, 'registration/register.html', context)
			

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, 
		shrink-to-fit=no">
	<title>Learning Log</title>

	{% bootstrap_css %}
	{% bootstrap_javascript jquery='full' %}

</head>
<body>
	<!-- expand一定不要写错（我开始写成了expend，找错找了一个小时。。。），否则会被自动折叠 -->
	<nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

		<a class="navbar-brand" href="{% url 'learning_logs:index'%}">
			Learning Log 爱蟹宝
		</a>

		<button class="navbar-toggler" type="button" data-toggle="collapse" 
			data-target="#navbarCollapse" aria-controls="navbarCollapse" 
			aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarCollapse">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item">
					<a class="nav-link" href="{% url 'learning_logs:topics' %}">Topics</a>
				</li>
			</ul>
			<ul class="navbar-nav ml-auto">
				{% if user.is_authenticated %}
					<li class="nav-item">
						<span class="navbar-text">Hello, {{ user.username }}.</span>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
					</li>
				{% else %}
					<li class="nav-item">
						<a class="nav-link" href="{% url 'users:register' %}">Register</a>
					</li>
					<li class="nav-item">
						<a class="nav-link"  href="{% url 'users:login' %}">Log in</a>
					</li>
				{% endif %}
			</ul>
		</div>

	</nav>

	<main role="main" class="container">
		<div class="pb-2 mb-2 border-bottem">
			{% block page_header %}{% endblock page_header %}
		</div>
		<div>
			{% block content %}{% endblock content %}
		</div>
	</main>

</body>

</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}

{% block content%}
	<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }} </a></p>
	<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='POST'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name"submit">Save Changes</button>
{% endblock content %}

learning_logs/templates/learning_logs/entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}
{% block page_header %}
	<h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
	<p><a href="{% url 'learning_logs:delete_topic' topic.id %}">Delete topic</a></p>
	<p><a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a></p>

	{% for entry in entries %}
		<div class="card mb-3">
			<h4 class="card-header">
				{{ entry.date_added|date:'M d, Y H:i' }}
				<small><a style="float: right;" href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a></small>
			</h4>
			<div class="card-body">
				{{ entry.content|linebreaks }}
			</div>
		</div>
	{% empty %}
		<h4>There has no entry yet.</h4>
	{% endfor %}
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
<div class="jumbotron">
	<h1 class"dispaly-3">Track your learning.</h1>
	<p class="lead">make your own Learning Log, and keep a list of the topics you're learning about. 
		Whenrver you learn something new about a topic, make an entry summarizing what you've learned.
	</p>
	<a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">Register &raquo;</a>
</div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}

{% block content %}
	<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
	<p>Add a new entry:</p>
	<form action="{% url 'learning_logs:new_entry' topic.id %}" method='POST'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">Add entry</button>
	</form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
	<p>Topic Name:</p>
	<form action="{% url 'learning_logs:new_topic' %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name"submit">Add Topic</button>
	</form>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}
{% block page_header %}
	<h1>Topics</h1>
{% endblock page_header %}

{% block content %}
	<ul>
		{% for topic in topics%}
			<li>
				<h3><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>
			</li>
		{% empty %}
			<li><h3>topic has been added yet.</h3></li>
		{% endfor %}
	</ul>
	<h3>
		<a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>
	</h3>
{% endblock content %}